### ISSUE TITLE
проверка связи ????

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#1]

**Comment by 13587** [comment]
Саша!
Нужно добавить в паспорте муниципального уровня добавить строчки для заполнения: 
 1. Наименование органа местного самоуправления осуществляющих управление в сфере образования;
 2. Руководитель органа местного самоуправления, осуществляющих управление в сфере образования (Ф.И.О. полностью);
 3. Телефон руководителя органа местного самоуправления, осуществляющих управление в сфере образования.

**Comment by 13587** [comment]
![10b](https://cloud.githubusercontent.com/assets/16133720/11561957/de146e88-99db-11e5-80f8-b062aad7fe44.jpg)

**Comment by 13587** [comment]
так получи мои комментарии

**Comment by 13587** [comment]
не .....запуталась

**Comment by 13587** [comment]
можно ли в модуле "статистика" добавить в статистика "детально", с ошибками, т.е. у нас есть загрузили, не загрузили, а ещё нужно добавить с ошибками?

**Comment by superbatonchik** [comment]
не забывай ставить Label (справа найдешь Labels)

**Comment by superbatonchik** [comment]
> можно ли в модуле "статистика" добавить в статистика "детально", с ошибками, т.е. у нас есть загрузили, не загрузили, а ещё нужно добавить с ошибками?

Такие вещи тоже нужно отдельным Issue делать

**Comment by 13587** [comment]
пвапапрр

**Comment by 13587** [comment]
лрлрлл
