### ISSUE TITLE
Проблемы при Автозаполнении форм 

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#106]
Возникла проблема при выполнении автозаполнениия по форме ОО-1 (2016)
Формулы вбиты, шаблоны одинаковые, название проверили, все выверено:

![-1](https://cloud.githubusercontent.com/assets/16133720/19338853/5c56cdc4-9128-11e6-8d9b-b3e62cc07869.png)

выходит ошибка:

![-1](https://cloud.githubusercontent.com/assets/16133720/19338932/dd901062-9128-11e6-8052-8597d634abb8.png)

По факту, автозаполнения возможно произвести из форм МО в регион. А вот с уровня организаций в свод МО, нет возможности, выходит ошибку (см. выше)

**Comment by superbatonchik** [comment]
должны быть одинарные ковычки
вместо
`‘Раздел 2.1.1.2’!$AC$21 = ‘Раздел 2.1.1.2’!$AC$21`
нужно
`'Раздел 2.1.1.2'!$AC$21 = 'Раздел 2.1.1.2'!$AC$21`
программа вставляет их автоматически. Откуда они тут взялись

**Comment by 13587** [comment]
в программе забивали формулы проверки
так выдала программа
