### ISSUE TITLE
Корректировка модуля "Статистика"

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#12]
В модуле статистика нужно добавить:
-  подразделе "Статистика форм" И "Статистика форм (сводная)" , нужно добавить расположение форм по годам (раскидать по годами 2015, 2014, 2013). 
![default](https://cloud.githubusercontent.com/assets/16133720/11590741/67bd1802-9aa3-11e5-8baa-c1e2775463d9.jpg)
![1](https://cloud.githubusercontent.com/assets/16133720/11590769/a683a592-9aa3-11e5-8f99-72791ee0d56f.jpg)

- в подразделе "Статистика форм (детально)" добавить к группе "заполнено" и "не заполнено" ещё один вариант "с ошибками" (в данную группу будут входить организации, которые заполнили формы с ошибками и опозданиями, с ошибками)
![2](https://cloud.githubusercontent.com/assets/16133720/11590858/68d57d5a-9aa4-11e5-94a6-fa48b4bdcc66.jpg)

**Comment by superbatonchik** [comment]
ты не написала как нужно "раскидать по годам". поэтому посмотри так или не так

**Comment by 13587** [comment]
угу

**Comment by 13587** [comment]
не совсем то, просмотрю ещё раз, пропишу!

**Comment by 13587** [comment]
![08 12 15](https://cloud.githubusercontent.com/assets/16133720/11655344/09c29e84-9dbe-11e5-99c9-cbe4f6407afc.jpg)
лучше, если это будет выглядить именно так.

**Comment by 13587** [comment]
в подразделе "Статистика форм (детально)" добавить к группе "заполнено" и "не заполнено" ещё один вариант "с ошибками" (в данную группу будут входить организации, которые заполнили формы с ошибками и опозданиями, с ошибками)
2
