### ISSUE TITLE
Не сохраняется "запрос" при нажатии кнопки "вывести отчет" на рабочий стол

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#127]
При выведении запроса из форм (с уровня ОО) нажимаем на кнопку "вывести отчет", 
выдает оповещение 

![default](https://cloud.githubusercontent.com/assets/16133720/24037395/b4ce4328-0b0e-11e7-92d1-ca95032ab415.png)

 в свою очередь при нажатии кнопки "вывести отчет в exsel" , то  это возможно

![default](https://cloud.githubusercontent.com/assets/16133720/24037456/ea62586c-0b0e-11e7-956c-1ac167852445.png)

Вот на этих картинках видно, что все нормально, но запрос не сохраняется.... именно при нажатии кнопки "вывести отчет"

![default](https://cloud.githubusercontent.com/assets/16133720/24037454/ea619b16-0b0e-11e7-8b1c-b9f5c9449f86.png)

![default](https://cloud.githubusercontent.com/assets/16133720/24037457/ea62adb2-0b0e-11e7-8fb9-9ac641598799.png)

![default](https://cloud.githubusercontent.com/assets/16133720/24037455/ea619fe4-0b0e-11e7-8856-26a23678cfca.png)

**Comment by superbatonchik** [comment]
Добавил логи, посмотрим, получится ли выяснить причину
