### ISSUE TITLE
Не соотвествует время загрузки форм Астрахань

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#144]
Не соотвествует время загрузки форм в программе загрузили форму для примера:
время загрузки по нашему 11.11, а на форме отображается время загрузки 10.11

![11 11](https://user-images.githubusercontent.com/16133720/34244814-84b2cf02-e640-11e7-8cb7-aef271e9ef3a.png)

* разница на 1 час, но раньше было все норм

**Comment by superbatonchik** [comment]
Решено
