### ISSUE TITLE
Добавление запрашиваемой информации в паспорт ОО

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#19]
Минобрнауки понадобились новые сведения об образовательной организации (ОО). Данные запрашивали, но только с уровня школ. Но возникла потребность запросить данные сведения у всех ОО, при этом данная информация может изменяться. Поэтому нужно (очень нужно)  добавить  строчки именно в паспорт ОО. 
Строчки, которые нужно добавить: 
- ИНН
- КПП
- ОГРН

![14 12 15](https://cloud.githubusercontent.com/assets/16133720/11776659/e1026c0e-a259-11e5-9218-050e577a57bd.jpg)
и добавить ещё один  раздел, где уже есть две вкладки лицензия и аккредитация: 
Плановая проверка (дата)
![14 12 15](https://cloud.githubusercontent.com/assets/16133720/11776664/e89ce8cc-a259-11e5-8ec3-44460d138e5e.jpg)

Саша, вот ещё в строчке "оператор" в скобках укажи, пожалуйста, (Ф.И.О.) - для особенных операторов!!! - будет выглядить вот так "Оператор (Ф.И.О.)"

**Comment by superbatonchik** [comment]
ИНН
    КПП
    ОГРН
это что? произвольный текст? может есть какой-то формат? ограничения по количеству символов?
как будто я знаю

**Comment by 13587** [comment]
ИНН
Идентификационный номер налогоплательщика (сокр. ИНН) — цифровой код, упорядочивающий учёт налогоплательщиков в Российской Федерации. Присваивается как юридическим, так и физическим лицам. Организациям присваивается с 1993 года, индивидуальным предпринимателям — с 1997 года, прочим физическим лицам — с 1999 года (с начала действия первой части Налогового кодекса Российской Федерации). 

ИНН в России бывает двух типов: ИНН организации — 10-значный и ИНН физического лица или ИП 12-значный.

Общая структура ИНН при этом похожа.

Так 10-значный ИНН организаций состоит из следующих частей:

4 цифры — код подразделения ФНС России (справочник СОУН)
5 цифр — номер налогоплательщика уникальный в рамках данного подразделения ФНС
1 цифра — проверочный код согласно коду проверки
ИНН физического лица состоит из 12-цифр, отличается незначительно и состоит из:

4 цифры — код подразделения ФНС России (справочник СОУН)
6 цифр — номер налогоплательщика, уникальный в рамках данного подразделения ФНС
2 цифры — проверочный код согласно коду проверки
Про то как проверить коды ИНН можно подробнее прочитать по ссылке http://www.polytech.ural.ru/checkvalues.htm

Я остановлюсь подробнее о том какую информацию ИНН в себе несёт.

1. По ИНН всегда и однозначно можно определить регион организации/физ. лица поскольку код подразделения ФНС состоит из кода региона + кода подразделения ФНС внутри данного региона. Код региона при этом соответствует порядковому номеру региона в Конституции РФ — по аналогии с автомобильными номерами и так далее.

2. По коду подразделения ФНС можно, с некоторой погрешностью, определить месторасположение подразделения и область которую оно покрывает, соответственно месторасположение лица/юрлица. Для юр. лиц это слабоактуально поскольку информация по их месторасположению и так доступна онлайн с большими подробностями, по физ. лицам такой информации онлайн нет, да и не должно быть.

3. Номер налогоплательщика — это инкрементальное число. Если приглядется и просмотреть хотя бы несколько ИНН, то можно обратить внимание что чем позже зарегистрирована организация тем это число больше. Соответственно зная даты регистраций нескольких организациях на интервалах значений можно с некоторой вероятностью предположить время выдачи ИНН по другой организации. Впрочем извлечение этой информации для ИНН организаций неактуальна поскольку информация о дате выдачи ОГРН/ИНН и так предоставляется ФНС онлайн.

4. Имеется возможность проверить ИНН как по контрольному коду, так и по реестру ЕГРЮЛ предоставляемом ФНС в публичной части в http://egrul.nalog.ru/fns/

                                                                   КПП

Код причи́ны постано́вки на учё́т (КПП) представляет собой девятизначный цифровой код, который вместе с ИНН организации позволяет однозначно идентифицировать её обособленные подразделения (см. КПП в Википедии).

Структура КПП:

4 цифры — код подразделения ФНС России (справочник СОУН);
2 цифры — код причины постановки на учёт;
3 цифры — порядковый номер постановки на учёт;
В большинстве случаев КПП выглядит как: код подразделения ФНС + 01001 поскольку не так уж много организаций имеют обособленные подразделения.

К недостаткам КПП можно отнести невозможность проверки КПП по контрольной сумме. Максимум можно проверить «разумность» заполнения каждого из его элементов. В общем случае КПП не несёт больше информации чем несёт ИНН, и практически никогда не используется по отдельности в ИНН организации.

                                                          ОГРН

ОГРН (основной государственный регистрационный номер) — государственный регистрационный номер записи о создании юридического лица либо записи о первом представлении в соответствии с Федеральным законом «О государственной регистрации юридических лиц» сведений о юридическом лице, зарегистрированном до введения в действие указанного Закона (пункт 8 Правил ведения Единого государственного реестра юридических лиц) (см. ОГРН в Википедии).

Структура ОГРН:

1 цифра — код, признак ОГРН (всегда равен 1);
2 цифры — две последние цифры года внесения записи в государственный реестр;
2 цифры — код региона по перечню регионов в 65-й статье Конституции
7 цифр — порядковый номер записи от начала года;
1 цифра — проверочный код ОГРН;
Что можно узнать зная ОГРН:

1. Год регистрации организации по двум последним цифрам.

2. С некоторой точностью месяц (а может быть и неделю) регистрации организации по порядковому номеру записи.

3. Код региона организации по 65-й статье Конституции.

4. По коду ОГРН может быть получена иная публичная информациия по организации — ИНН, КПП, наименование, адрес из публичного реестра ФНС.

Можно обратить внимание что ИНН и ОГРН отличаются принципами ведения порядковых номеров организаций. Если в ИНН они привязаны к налоговой инспекции, то в ОГРН к году регистрации. Соответственно исходя из возможности по порядковому номеру ИНН определить дату его присвоения, можно говорить что ИНН несёт чуть больше информации (номер инспекции) чем ОГРН.

**Comment by 13587** [comment]
КПП - цифры 9 (знаков), ОГРН - 13 цифр, ИНН - 10 цифр
Все данные указываются (прописываются) - цифры БЕЗ ПРОБЕЛОВ, БЕЗ ТОЧЕК, БЕЗ ДИФ., ПРОСТО ЦИФРЫ
