### ISSUE TITLE
Наслоение в наименовании

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#21]
![1](https://cloud.githubusercontent.com/assets/16133720/11869879/191f1c1e-a4d4-11e5-80d3-b7237cf22ecd.jpg)
![default](https://cloud.githubusercontent.com/assets/16133720/11869886/2c273206-a4d4-11e5-88f7-a01600c96e94.jpg)
Наслоение наименование форм загруженных организацией! Почему так происходит!? Надо исправить!

**Comment by superbatonchik** [comment]
не воспроизводится

**Comment by 13587** [comment]
Ты не смог просмотреть данный фрагмент?

**Comment by 13587** [comment]
![21 12 15](https://cloud.githubusercontent.com/assets/16133720/11929922/270963d8-a7f0-11e5-9951-bffa1e69e7ab.jpg)
Вот сегодня при просматривании форм обнаружила - в СОШ № 37 г. Астрахань
