### ISSUE TITLE
не выводить запрос с уровня МО!

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#27]
При выгрузки запроса с уровня муниципалитетов, выходит ошибка	

![22 01 16](https://cloud.githubusercontent.com/assets/16133720/12507806/34cbd8ca-c109-11e5-8349-9381d382aebd.jpg)

	
C:\Users\User\Desktop\22.01.16, что это.jpg
Подробная информация об использовании оперативной 

(JIT) отладки вместо данного диалогового 

окна содержится в конце этого сообщения.

************** Текст исключения **************

System.ArgumentException: Элемент с тем же ключом уже был добавлен.

в System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)

в EduFormManager.Forms.UserControls.QueryControl.QueryCheckListControl.Initialize()

в EduFormManager.Forms.UserControls.QueryControl.XtraQueryMunicipalityControl.<OnIndexChangedSetDataSourceFor>d__9.MoveNext()

-— Конец трассировка стека из предыдущего расположения, где возникло исключение —-

в System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

************** Загруженные сборки **************

mscorlib

Версия сборки: 4.0.0.0

Версия Win32: 4.0.30319.34209 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

----------------------------------------

System

Версия сборки: 4.0.0.0

Версия Win32: 4.0.30319.34238 built by: FX452RTMGDR

CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

----------------------------------------

EduFor

![22 01 16](https://cloud.githubusercontent.com/assets/16133720/12507878/977d7eec-c109-11e5-88b6-dcd2241878e2.jpg)

При нажати отмена, программа спрашивает "выйти из приложения", отметила нет, программа закрылась.

**Comment by superbatonchik** [comment]
тут поподробнее плз. у меня не получилось воспроизвести
