### ISSUE TITLE
Критично! Блокировка форм не работает!!!

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#31]
!!!!   ;((((    Критично! Блокировка форм не работает!!!
Саша, при блокировки форм вышло вот такая оказия. Сама проделала всю операцию по-шагова, что у нас получается: закончился срок сдачи формы (например Д-13 ОО подвед., срок сдачи был 13.01.2016), при желании мы можем загрузить форму в любом случаи (из файла, из шаблона), отметка - с опозданием. Блокировка срабатывает только лишь, на то "если форма загружена, то программа не позволяет производить корректировки и удалить форму..... 
Да,  кстати, так можно поступить и с архивными формами.... имею ввиду, что это касается все форм и доп.форм и фсн, 2014,2015 и текущего года. 
 НО это не дело.

![default](https://cloud.githubusercontent.com/assets/16133720/12579775/8f63e8ce-c43b-11e5-8018-c690c5ae032b.jpg)

 Если срок сдачи формы закончился, то программа не должна позволять - не подгружать , не удалять  и не скорректировать формы.....    
Мы позиционируем:  "все ребята, вы не успели загрузить форму, плохо.... не можете и не имеете право...., только лишь после официального письма операторам будет предоставлена возможность подгрузки, корректировки и т.д... 
И вот-тут то выползает  2 момент. 

![default](https://cloud.githubusercontent.com/assets/16133720/12579900/73a12bbe-c43c-11e5-9023-54ab19e55770.jpg)

При фиксации формы в модуле "справочник"  , подмодуль "формы"  
мы проставляем тип организации и выбираем МО и /или ОО на уровне которых не должна отображаться форма! 

![1](https://cloud.githubusercontent.com/assets/16133720/12579980/f7b13a02-c43c-11e5-9cce-b5c8b46a727b.jpg)
 
![2](https://cloud.githubusercontent.com/assets/16133720/12579984/fbaad190-c43c-11e5-82ce-1df43ec8721f.jpg)

НО , ПО-СУТИ  (ПРОСМАТРИВАЛА, ЭКСПЕРИМЕНТИРОВАЛА, РЕАЛЬНО ИМЕННО ТАК) форма отображаться у всех, у кого надо и не надо.... и получается, что например (утрирую) заполнили все кому не лень, или чрезмерно ответственные, при выгрузки запросов, получаем корявые данные и начинается все с начала ... разборки.

НАДО: чтобы программа после окончания срока сдачи формы - блокировала форму, именно блокировала, чтобы операторы не могли не подгружать форму, не исправлять , не удалять....
Чтобы при проставлении блокировки формы -  с указание определенного типа, МО и конкретной ОО, так и было, форма не отображалась у тех кому на неё поставлена блокировка.
Соответственно, при необходимости разблокировки формы, мы могли разблокировать формы именно для организации и  муниципалитета, которым будет проставлен доступ, а у кого будет стоять блокировка - с формой не смогут сделать ни чего.....

**Comment by superbatonchik** [comment]
хоспаде. Тебе надо научиться выражать свои мысли. Надеюсь, я правильно понял, что нужно было лишь добавить блокировку загрузки формы по истечении срока сдачи?

**Comment by 13587** [comment]
с детьми всегда все разжёвывала, и проговаривала не сколько раз подряд. Да. правильно понял.

**Comment by superbatonchik** [comment]
Ты проверяла? надо закрывать, если все нормально.

**Comment by 13587** [comment]
Нет, не работает! Пробовала с уровня школы, спокойно загрузила форму из шаблона и из файла, ....(подчеркиваю )с учетом,что форма заблокирована!!!!!

**Comment by superbatonchik** [comment]
да все там работает
