### ISSUE TITLE
Вариант ответить операторам на сообщение в программе!?!

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#33]
Задача:
- нужно придумать и реализовать возможность отвечать на сообщения, которые приходят от операторов. РАБОТА В МОДУЛЕ "сообщения"

![default](https://cloud.githubusercontent.com/assets/16133720/12581241/7496e720-c446-11e5-9bb6-24ad15f2ee05.jpg)

В данные момент связь односторонняя. 

![1](https://cloud.githubusercontent.com/assets/16133720/12581246/7c81df62-c446-11e5-9963-4816c0d3ee2e.jpg)

Саша, но  сейчас возникла необходимость обратной связи.
Причин достаточно, поэтому извини перечислять не буду.
НО нужно!

**Comment by superbatonchik** [comment]
пока не вариант

**Comment by 13587** [comment]
хорошо, но надо держать данную задачу на заметке!

**Comment by 13587** [comment]
По данной задаче, нам сейчас, очень важно, чтобы министерство видело, какой оборот вопросов поступает и соответственно ответов. По телефону - это хорошо, но нужно, чтобы было в живой ленте!

**Comment by 13587** [comment]
Необходимо решить данный вопрос. Я предполагаю, что сейчас именно то время, когда можно безболезненно решить эту проблему для всех.

**Comment by superbatonchik** [comment]
Не будем реализовывать
