### ISSUE TITLE
Добавить доп.формы региона

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#37]
В принципе модуль "доп.формы  регион" есть. Но мы не можем  создать дополнительные формы для региона, ....соответственно не загрузить, не просмотреть и т.д.

рисунок 1

![default](https://cloud.githubusercontent.com/assets/16133720/12782794/9c529766-ca8e-11e5-9947-223c7bfd7a2d.jpg)

рисунок 2
![1](https://cloud.githubusercontent.com/assets/16133720/12782795/9c539846-ca8e-11e5-9191-e5e707381299.jpg)

Когда я попыталась выгрузить запрос с уровня региона вышла вообще ошибка, СТРАШНАЯЯЯЯЯЯ
![2](https://cloud.githubusercontent.com/assets/16133720/12782797/9c57204c-ca8e-11e5-97ca-8ceb0cd89987.jpg)

![3](https://cloud.githubusercontent.com/assets/16133720/12782796/9c569d70-ca8e-11e5-8bfe-d1a3f00eb858.jpg)

![4](https://cloud.githubusercontent.com/assets/16133720/12782798/9c5a9fe2-ca8e-11e5-9291-316c20814ba5.jpg)

**Comment by superbatonchik** [comment]
> Но мы не можем создать дополнительные формы для региона

Не понял я что-то
Справочники -> формы -> новая форма -> в списке типов выбираешь доп. формы регион и все
