### ISSUE TITLE
Оповещение

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#39]
Выставила срок сдачи формы, например: сведения о детях школьного возраста (отстающие) срок заполнения выставила 04.02.16 17.00 у муниципалитетов в оповещении

![default](https://cloud.githubusercontent.com/assets/16133720/12784998/5060de82-ca9b-11e5-9115-0f265544fa31.jpg)
  
то есть, по оповещению видно, что у них остался срок до завтра 17.00,
а мне нужно, именно чтобы они заполнили форму до 17.00 03.02.16, если я им выставляю срок до 03.02.16 17.00, они загружают форму с опозданием...
Помоги в этом вопросе, как быть!
Или надо что-то перенастроить!

**Comment by superbatonchik** [comment]
исправил
