### ISSUE TITLE
Выгрузка запроса из паспорта ОО

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#40]
![default](https://cloud.githubusercontent.com/assets/16133720/12785583/3f97d7a6-ca9e-11e5-9668-ffcea67c7a1a.jpg)
При выгрузки запроса из паспорта ОО по нескольким муниципалитетам, проблемы:
* все организации выгружаются в вперемешку независимо от муниципалитета (на картинке видно,  организации муниципалитета г.Астрахани  и Знаменска)
* и данные выгружаются с формулировкой "не удалось"  
(у нас уже такая проблема возникала, и её уже решали)
Если это не ошибка, то формулировка "не удалось" не корректна, надо просто "пустоту" 
Именно по пунктам ИНН, ОГРН, ОКПО. 
Но иногда ОКПО выгружается нормально!!!

![1](https://cloud.githubusercontent.com/assets/16133720/12785761/14bee26c-ca9f-11e5-8bc1-b7d0a17dd682.jpg)

**Comment by superbatonchik** [comment]
это не ошибка. Пустоту и сортировку добавил.
"иногда" не может нормально выгружаться. Там почти ни у кого не заполнено инн, кпп и т.д.
