### ISSUE TITLE
Проблемы с созданием и выгрузкой запросов с уровня ОО и МО

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#43]
Возникшие проблемы при создании и выгрузки запросов с уровня ОО и МО

2016-02-09 16:55:10.1887 app ERROR The Connection is broken. 
2016-02-09 16:55:10.2887 app ERROR в Npgsql.ForwardsOnlyDataReader.Read() 
в System.Data.Common.DbDataReader.ReadAsync(CancellationToken cancellationToken) 
-— Конец трассировка стека из предыдущего расположения, где возникло исключение —- 
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
в System.Data.Entity.Core.Objects.Internal.ShapedBufferedDataRecord.<InitializeAsync>d__4.MoveNext() 
-— Конец трассировка стека из предыдущего расположения, где возникло исключение —- 
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
в System.Data.Entity.Core.Objects.Internal.BufferedDataReader.<InitializeAsync>d__0.MoveNext() 
-— Конец трассировка стека из предыдущего расположения, где возникло исключение —- 
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
в System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.<ExecuteAsync>d__0`1.MoveNext() 
-— Конец трассировка стека из предыдущего расположения, где возникло исключение —- 
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
в System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__3b`1.MoveNext() 
-— Конец трассировка стека из предыдущего расположения, где возникло исключение —- 
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
в System.Data.Entity.Core.Objects.ObjectQuery`1.<GetResultsAsync>d__12.MoveNext() 
-— Конец трассировка стека из предыдущего расположения, где возникло исключение —- 
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
в System.Data.Entity.Core.Objects.ObjectQuery`1.«System.Data.Entity.Infrastructure.IDbAsyncEnumerable<T>.GetAsyncEnumerator>b__1>d__2.MoveNext() 
-— Конец трассировка стека из предыдущего расположения, где возникло исключение —- 
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
в System.Data.Entity.Internal.LazyAsyncEnumerator`1.<MoveNextAsync>d__1.MoveNext() 
-— Конец трассировка стека из предыдущего расположения, где возникло исключение —- 
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
в System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<ForEachAsync>d__5`1.MoveNext() 
-— Конец трассировка стека из предыдущего расположения, где возникло исключение —- 
в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
в EduFormManager.Forms.MainForm.<windowsUIViewMain_QueryControl>d__6f.MoveNext()
1

![83- 2015](https://cloud.githubusercontent.com/assets/16133720/13007721/2fecf1b8-d1a3-11e5-8d63-50ea2d84de18.jpg)

*Саша, а сегодня, просто пыталась выгрузить запрос из формы 83-рик 2015, вышла опять вот эта ошибка, после нажатия на "ОК", программа зависла, выключать программу можно только через диспечер-задач
*про создании запроса по форме 83-рик 2014 , программа не сохраняет все мой внесенные запросы
![83- 2014](https://cloud.githubusercontent.com/assets/16133720/13007848/f095702a-d1a3-11e5-854f-5095112667b8.jpg)
![83- 2014_ 1](https://cloud.githubusercontent.com/assets/16133720/13007859/fcc8707c-d1a3-11e5-834c-c17ce051c8f0.jpg)
![83- 2014_](https://cloud.githubusercontent.com/assets/16133720/13007858/fcc57d22-d1a3-11e5-99da-1b6a49ace5e3.jpg)

![83- 2015](https://cloud.githubusercontent.com/assets/16133720/13007863/032adbd0-d1a4-11e5-867d-3c4ad37f2bec.jpg)

а самое обидное я неделю сидела и создавала запросы по формам ош-1, ош-5, 83-рик, ош-2 за 2014 и 2015 год..... а половина почемуто нет😢
уже надоело, как буд-то кто берет и все удаляет, что за ерунда....
вот видно, что все создано,

**Comment by superbatonchik** [comment]
Про ошибку с "элемент с таким ключом уже добавлен" понятно - кто-то сделал два одинаковых запроса, один из которых отличался от другого лишним пробелом, который обрезается по умолчанию. Сделал короче проверку дополнительную, чтобы не было ошибки, но лучше не создавать запросы с одинаковыми именами но лишними пробелами и все такое.

Про "лист с такми именем не найден" думаю тебе тоже должно быть понятно. Надо просто исправить в запросе адрес ячейки.

Про несохранение запросов хз, я создал два запроса все ок.

**Comment by 13587** [comment]
создавала запросы, не всегда сохраняет все и порой специально нужно переименовывать запрос, т.к. не всегда после создания отображается. например создаю запрос к форме ВПО-1 и СПО-1 (уровень организаций разный ячейки для выгрузки данных разные, а наименование показателя одинаковое, ьак вот , программе не всегда принимает одинаковые наименование по показателям)

**Comment by 13587** [comment]
нужно просмотреть более подробно

**Comment by 13587** [comment]
Сегодня создавала запрос к форме 1-ДО:
создала
![default](https://cloud.githubusercontent.com/assets/16133720/13317362/ff6c3f94-dbc5-11e5-862f-0b147676fc62.jpg)
сохранила, но не тут то было
![default](https://cloud.githubusercontent.com/assets/16133720/13317383/1aa13f26-dbc6-11e5-9024-88f5c9addfb8.jpg)
переименовала, сохранила
![default](https://cloud.githubusercontent.com/assets/16133720/13317386/27f43f48-dbc6-11e5-8c14-48d1c8fe7087.jpg)
и вот, пожалуйста, все есть
![default](https://cloud.githubusercontent.com/assets/16133720/13317406/352dfdc0-dbc6-11e5-8b11-7862380bde3c.jpg)

**Comment by superbatonchik** [comment]
проверь еще раз
