### ISSUE TITLE
Ошибка у организации с вкладкой для выбора формы   

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#44]
Саша, возникла проблема у организации дополнительного образования "Центр развития творчества", при загрузки формы у них не выпадает дополнительное меню с доп.формами.....
а сегодня ещё выявила и организаций типа СПО  «Астраханский агротехнический техникум»

![default](https://cloud.githubusercontent.com/assets/16133720/13195243/8d405ff0-d7be-11e5-90c2-38a79934c91e.jpg)

![default](https://cloud.githubusercontent.com/assets/16133720/13070677/5ac958be-d49f-11e5-9f43-f3342f136b5e.jpg)

обычно выпадает две категории форм: фсн организации  и доп.формы организации, а у них только фсн, именно у них

**Comment by superbatonchik** [comment]
Ничего удивительного. У них не отмечено ни одной доп. формы, поэтому и нет в меню.

![3](https://cloud.githubusercontent.com/assets/14849137/13248631/7d8554c0-da30-11e5-8840-fb559ab5f814.png)

**Comment by 13587** [comment]
так и нет в выпадающем меню строчки с доп.формами
![Uploading так и нет доп.форм.jpg…]()
