### ISSUE TITLE
Возможность функционирования кнопок при открытии программы!

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#49]
При открытии программы нет возможности свернуть или свернуть в окно, т.е. программа  раскрывается и все... это не совсем удобно... Нет возможности открыть другой файл ... и т.д.

![default](https://cloud.githubusercontent.com/assets/16133720/13420076/1d11400e-df94-11e5-9c99-c5826c0ac4d7.jpg)

данные кнопки не работают, пока не введешь пароль

![1](https://cloud.githubusercontent.com/assets/16133720/13420106/5f762a40-df94-11e5-9cdc-2e4a9c2fa6fe.jpg)

**Comment by superbatonchik** [comment]
не получится. Так работает диалоговое окно.

**Comment by 13587** [comment]
все теперь функционирует
