### ISSUE TITLE
Цветовая индикация.

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#5]
Цветовая индикация не правильно работает. Возьмем к примеру муниципалитет "Наримановский район". Если мы заходим в модуль "архив фсн", мы там видим, образовательные организации, они окрашены и внесены в группу "с ошибками". Заходим в раскладку именно по каждому учреждению, там мы видим, что у все учреждений все хорошо, т.е. они в группе "ОК".
(подчеркиваю,  у всех учреждений все формы заполнены без ошибок и опозданий). Тогда возникает вопрос, почему при входе в муниципалитет (где мы видим организаций распределенные по типам: образовательные организации, дошкольные организации, организации дополнительного образования) тип образовательной организации находиться в группе "с Ошибками"

**Comment by superbatonchik** [comment]
у некоторых организаций есть загруженные муниципалитетные формы. они учитываются при подсчете статистики, но не выводятся при просмотре форм организации. Если их удалить, то все должно быть нормально.

**Comment by 13587** [comment]
пока подожди

**Comment by 13587** [comment]
у некоторых организаций в действительности есть загруженные муниципальные формы, но это как раз и правильно, т.к. подведомственные организации заполняют формы(как у муниципалитетов). Поэтому удалять не надо.
