### ISSUE TITLE
Сортировка организаций от 1 до ....

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#54]
![Uploading сортировка организаций от 1 до .....!.jpg…]()

Необходимо произвести сортировку образовательных организаций, очень трудно найти учреждение (например: г.Астрахань детские сады - их там 82)

по скриншу видно, как они разбросаны 

![1](https://cloud.githubusercontent.com/assets/16133720/13702270/5d1cba18-e79e-11e5-90ea-588964775bcc.jpg)
 
![Uploading сортировка организаций от 1 до .....!.jpg…]()

**Comment by superbatonchik** [comment]
Они не разбросаны, а отсортированы. Название организации, в котором есть какой-то номер, не означает, что сортировка будет производиться по этому номеру. Например, есть числа в виде строк 1, 2, 100, 110. Отсортированы они будут так: 1, 100, 110, 2. Чтобы сортировать еще и по номеру, то этот номер нужно выносить в отдельное поле. В форме заполнения данных об организации должны быть поля типа "наименование" (туда пишешь детский сад), "номер" (туда пишешь номер или ничего не пишешь, если номера нет) и дальше все остальные поля, которые у нас есть.

**Comment by superbatonchik** [comment]
можно сделать, если надо.

**Comment by 13587** [comment]
Надо  -  Саша! Надо!!!

**Comment by 13587** [comment]
Саша, по образовательным организациям (школы все хорошо, а вот по дошкольным организациям не совсем)

![default](https://cloud.githubusercontent.com/assets/16133720/14595440/dac7e0fc-0547-11e6-8f20-ecbbea55616d.jpg)


![default](https://cloud.githubusercontent.com/assets/16133720/14595439/dac586d6-0547-11e6-9332-2b4941b56334.jpg)
