### ISSUE TITLE
Изменение формулировки "отчет 2"

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#56]
Изменение формулировки "вывести отчет"   и   "Вывести отчет 2" - мой предложения, что бы было более понятно всем.... я первый раз тоже не сразу все поняла.
Давай переименуем вот так, т.к. это выведение запроса, пусть будет "Вывести отчет" - "Вывести запрос" ,  а  "Вывести отчет 2 " - "Предварительный просмотр запроса"

![default](https://cloud.githubusercontent.com/assets/16133720/13703239/94f0b0fa-e7a5-11e5-89bb-ded8275eca25.jpg)

> возможны  дебаты к формулировкам

**Comment by superbatonchik** [comment]
та не, "вывести отчет 2" лучше сделать так "вывести отчет в Excel". В идеале конечно вместо Excel надо написать электронная таблица, но это слишком длинное название

**Comment by 13587** [comment]
* принимаю твой вариант
