### ISSUE TITLE
Выгрузка запроса (после выгрузки из программы с данным файлом невозможно работать, нельзя вбить формулы...

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#59]
Выгружая запрос из формы, когда пользуюсь функцией "вывести отчет 2", вот, что интересно
выходит в документе с отображением 2 разных листов, при этом по логике, где указано "запрос", там должны быть сведения, но по факту там пусто, а вот в первом листе 1 - находятся данные

![-](https://cloud.githubusercontent.com/assets/16133720/13744507/39968616-e9f9-11e5-8ad1-b9cacf69f326.jpg)

![1 -](https://cloud.githubusercontent.com/assets/16133720/13744512/3de59ee6-e9f9-11e5-8483-7b42725ea8d3.jpg)

* это разве правильно?!?

Да, кстати, при сохранении файла на рабочий стол, у меня нет возможности ввести формулы проверки (свои заморочки), просто я не могу ввести элементарно "сумму".

формулу ввожу =
![1](https://cloud.githubusercontent.com/assets/16133720/13744624/0df57cd2-e9fa-11e5-8e21-0facced9bb5c.jpg)

а вот данные не получаю, выводит "0"

![default](https://cloud.githubusercontent.com/assets/16133720/13744638/2cf5529c-e9fa-11e5-9078-cac4262d46be.jpg)

**Comment by superbatonchik** [comment]
я вроде куда-то писал, что хз почему формулы не работают. проверь тип данных, может офис не распознает, что там не числа, а строки или еще что хз

**Comment by 13587** [comment]
не знаю, что там делать, формат ячейки меняла, все равно остается все по прежнему, проверяла  строчки, все нормально....
