### ISSUE TITLE
Надо разобраться с оповещением "сроки сдачи форм"

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#68]
# Надо разобраться с оповещением "сроки сдачи форм"

в общей картине все хорошо, но давай рассмотрим более детально:
- если я ставлю срок сдачи формы "Питание обучающихся в дневных ОО (1 кв. 2016г.) - 1 апреля в 15.00, программа в оповещениях на уровне МО  и ОО показывает, вот так  см. рисунок 
(что сдать форму нужно завтра до 15.01 -  т.е. они должны сдать форму до 31.03.16,  15.01) Это как так. 

![2](https://cloud.githubusercontent.com/assets/16133720/14142542/0c09eec0-f68f-11e5-807c-43883e3ab162.jpg)

*и тем самым если они загружают форму 31.03.16 до 15.00 - она у них отображается как с опозданием????? !!!!!!!

- если я ставлю срок по факту нужно 1 апреля 15.00, а я поставлю 2 апреля 15.00 - опозданий у них не будет, но вот в оповещениях операторы видят, что до сдачи формы ещё осталось 2 дня.

И операторы рады стараться, что им нужно сдать форму теперь уже получается не 1 апреля .... ты понял.....

****надо решить данную проблему?????

И вот ещё, это больше относиться к уточнению - обновления программу работают автоматически, у нас там все хорошо..... Приходиться закрывать программу и производить вход заново!!!

**Comment by superbatonchik** [comment]
> И вот ещё, это больше относиться к уточнению - обновления программу работают автоматически, у нас там все хорошо..... Приходиться закрывать программу и производить вход заново!!!

что простите?

**Comment by 13587** [comment]
здесь я имела ввиду, что:  обновления программу работают автоматически, у нас там все хорошо ????? т.к. возникают такие моменты когда, если что-то было исправлено или скорректировано ...нужно закрыть программу и только после этого были видны внесенные изменения....
Ранее такая проблема была, потом устранена, но сейчас периодически возникает заново.

**Comment by 13587** [comment]
Могу тебе направить файл со списком форм фсн, если это нужно для уточнения по срокам сдачи!
