### ISSUE TITLE
Разработка 4 модулей "Регион" 

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#7]
Очень важная задача, которую надо реализовать в течение месяца (декабрь), разработка и добавление модулей:
- форма ФСН (Регион)
- доп.формы (Регион)
- архив форм ФСН (Регион)
- архив доп.форм (Регион)

Данные модули должны отображаться на уровне минобрнауки, и соответственно на нашем. Но ещё важный момент, формы должны работать так же как и модули организаций и муниципалитетов, а мы как админ. должны загружать форму регионального уровня. При этом очень важно, что бы это было реализовано к концу месяца.

**Comment by superbatonchik** [comment]
> формы должны работать так же как и модули организаций и муниципалитетов, а мы как админ
не понял
> реализовано к концу месяца
какого месяца?

**Comment by 13587** [comment]
до конца декабря

**Comment by 13587** [comment]
я имела ввиду, что модули регион работают по такому же принципу как и все остальные модули (организаций и муниципалитетов). Но подгружать информацию в данных модулях будем мы (с уровня админки)
