### ISSUE TITLE
Что-то странное и непонятное.....

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#75]
Саша, просматриваю формы , я надкнулась, в прямом смысле этого слова, на интересную цветовую индикацию...
смотри, организации дополнительного образования, выделены (рисунок)

![default](https://cloud.githubusercontent.com/assets/16133720/14428262/0b21d614-0001-11e6-941a-ce462281c129.jpg)

ладно, заходим, видим всего одну организацию, у которой все хорошо, ---- но почему они тогда в группе "с опозданием и ошибки"

![default](https://cloud.githubusercontent.com/assets/16133720/14428263/0b21e1cc-0001-11e6-8d2a-ebc16668c669.jpg)

смотрим дальше , что видим, оп.... 
а формы все без проблем и ошибок, ????? 

![1](https://cloud.githubusercontent.com/assets/16133720/14428276/10887504-0001-11e6-994b-2bf52d1023dc.jpg)

*так почему так произошло????

**Comment by superbatonchik** [comment]
это из-за муниципальных форм, которые загружают организации, как ты говорила. ты уже спрашивала

**Comment by 13587** [comment]
не понялда.....
