### ISSUE TITLE
Добавить функции предусмотренные Exsel при выведении отчетов

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#76]
Добавить функции  предусмотренные Exsel (все предусмотренные форматы ячеек) при заполнении шаблона и соответственно при выведении данных через сформированный запрос 
в программе.

![1](https://cloud.githubusercontent.com/assets/16133720/14526171/367e9004-024a-11e6-8b0e-7ff697221c73.jpg)

![2](https://cloud.githubusercontent.com/assets/16133720/14526155/17b873f6-024a-11e6-8e51-756dea4746f3.jpg)

**Comment by superbatonchik** [comment]
о может мне собственный эксель написать
