### ISSUE TITLE
Отображение оповещений на уровне МО и ОО

### ISSUE THREAD

**Issue by 13587** [superbatonchik/EduFormManager#77]
Саша, а у нас вышла вот такая интересная штука:

пример:
на уровне МО вышло оповещение 

![default](https://cloud.githubusercontent.com/assets/16133720/14597055/1b014cd4-0553-11e6-8d09-1654690320c3.jpg)

*Но стоит заметить, что данная форма загружалась в срок до 15.05.2015г. 23.00

![15 05](https://cloud.githubusercontent.com/assets/16133720/14597124/895326b2-0553-11e6-989b-0d6914fdf600.jpg)

![15 05](https://cloud.githubusercontent.com/assets/16133720/14597129/8eca37c0-0553-11e6-9162-9013bd0d3f6c.jpg)

Предполагаю, что в программе установлено фиксирование по дате (день и месяц, а вот год учитывается). Надо подправить, чтобы учитывался и год, поясню почему, есть формы в ряде таких как доп.формы,  они могут быть однократные, т.е. собираться только один раз, и все.... 
Сань., отрегулируй, пожалуйста, данный момент.
 Спасибо!

**Comment by superbatonchik** [comment]
для всех форм правила одинаковы типа форма загружается раз в год. напиши какие есть еще исключения, помимо того, что какая-то форма должна загружаться единожды, чтобы больше не возвращаться к этому. потому что это дикая подстава для меня, впрочем как и всегда

**Comment by 13587** [comment]
[для Саши.xlsx](https://github.com/superbatonchik/EduFormManager/files/285850/default.xlsx)

 вот файл в нем формы фсн, расписано что и когда, это для информации, есть ещё доп. формы, но с ними что-то на подобие, т.е. я имею ввиду есть формы доп. годовые, ежеквартальные , одно кратные....
